//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int App_ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Emp_Name { get; set; }
        public int Leave_Days { get; set; }
        public string Type_Leave { get; set; }
        public System.DateTime First_Day { get; set; }
        public System.DateTime Last_Day { get; set; }
        public string Reason_Leave { get; set; }
        public int Emp_ID { get; set; }
        public string App_Status { get; set; }
        public string standIn { get; set; }
        public byte[] Emp_SickNote { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
